#!/bin/bash

set -euo pipefail

NETSY_NODE_ID="$(hostname -s)"
NETSY_BIND_CLIENT=:2379
NETSY_ADVERTISE_CLIENT="$U7S_PARENT_IP:2379"
NETSY_BIND_PEER=:2380
NETSY_ADVERTISE_PEER="$U7S_PARENT_IP:2380"
NETSY_BIND_ELECTION=:2378
NETSY_ADVERTISE_ELECTION="$U7S_PARENT_IP:2378"
NETSY_BIND_HEALTH=:2381
NETSY_TLS_CA_CERT="$XDG_CONFIG_HOME/usernetes/node/ca.pem"
NETSY_TLS_SERVER_CERT="$XDG_CONFIG_HOME/usernetes/node/etcd-peer.pem"
NETSY_TLS_SERVER_KEY="$XDG_CONFIG_HOME/usernetes/node/etcd-peer-key.pem"
NETSY_TLS_CLIENT_CERT="$XDG_CONFIG_HOME/usernetes/node/etcd-peer.pem"
NETSY_TLS_CLIENT_KEY="$XDG_CONFIG_HOME/usernetes/node/etcd-peer-key.pem"
NETSY_DATA_DIR="$XDG_DATA_HOME/usernetes/netsy"
NETSY_DEBUG=false
AWS_DEFAULT_REGION=eu-central-1

export NETSY_NODE_ID \
	NETSY_BIND_CLIENT \
	NETSY_ADVERTISE_CLIENT \
	NETSY_BIND_PEER \
	NETSY_ADVERTISE_PEER \
	NETSY_BIND_ELECTION \
	NETSY_ADVERTISE_ELECTION \
	NETSY_BIND_HEALTH \
	NETSY_TLS_CA_CERT \
	NETSY_TLS_SERVER_CERT \
	NETSY_TLS_SERVER_KEY \
	NETSY_TLS_CLIENT_CERT \
	NETSY_TLS_CLIENT_KEY \
	NETSY_DATA_DIR \
	NETSY_DEBUG \
	AWS_DEFAULT_REGION
